### PR TITLE
Adds CHANGELOG file generated from github releases

### PR DESCRIPTION
**Pull request by b-onc**
I've used [this tool](https://github.com/rhysd/changelog-from-release) to create CHANGELOG

### CODE REVIEW

**Comment by buh** [comment]
How did you generate it?

**Comment by b-onc** [comment]
@buh Please see the PR description

**Comment by b-onc** [comment]
@tbarbugli The idea is to have a CHANGELOG we can keep updating. This repo did not have a chamgelog, but was using github releases for change logs. I've created the CHANGELOG so that we can continue using it (as we do in Chat repo)

**Comment by buh** [comment]
Please regenerate it. I updated the release notes.

**Comment by b-onc** [comment]
@buh Done

**Pull request merged**
